In [10]:
import numpy as np 
import random
import math

In [2]:
# Set a seed
random.seed(47) 
# Generate n nodes
def generate_nodes(n):
    nodes = []
    for x in range(1, n+1):
        for y in range(1, n+1):
            status = random.choice([0, 1])
            life_around = 0
            time = 0
            nodes.append([x, y, status, life_around, time])
    return nodes

nodes = generate_nodes(3)

In [3]:
nodes = np.array(nodes)
numb_nodes = int(math.sqrt(nodes.shape[0]))

# Problem A

## Status and Life around matrixes

In [4]:
def get_status(nodes):
    # +2 is to have zeroes as the borders
    matrix_status = np.zeros((numb_nodes+2, numb_nodes+2), dtype=int)
    for node in nodes:
        x, y, status, life_around, time = node
        matrix_status[x][y] = status
    return matrix_status

matrix_status = get_status(nodes)
matrix_status

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0]])

In [5]:
def get_life_around(nodes, matrix_status):
    matrix_life_around = np.zeros((numb_nodes+2, numb_nodes+2), dtype=int)
    for node in nodes:
        x, y, status, life_around, time = node
        # To consider the 8 nodes(=neighbours) around the current node I set this range
        for i in range(x-1, x+2):
            for j in range(y-1, y+2):
                # Skip the current node
                if i == x and j == y:
                    continue
                if matrix_status[i][j] == 1:
                    matrix_life_around[x][y] += 1
    return matrix_life_around

matrix_life_around = get_life_around(nodes, matrix_status)
matrix_life_around

array([[0, 0, 0, 0, 0],
       [0, 2, 5, 2, 0],
       [0, 4, 6, 3, 0],
       [0, 3, 4, 3, 0],
       [0, 0, 0, 0, 0]])

## Evolution function

In [12]:
def dynamic_system(my_nodes, n_steps):
    # Create a copy of the original nodes
    new_nodes = np.copy(my_nodes)
    matrix_status = get_status(my_nodes)
    matrix_life_around = get_life_around(my_nodes, matrix_status)
    for step in range(n_steps):
        # To avoid the zeros of the boundary (they aren't nodes) I set this range
        for i in range(1, len(matrix_status) - 1):
           for j in range(1, len(matrix_status) - 1):
                if matrix_status[i][j] == 1:
                    if matrix_life_around[i][j] < 2 or matrix_life_around[i][j] > 3:
                        matrix_status[i][j] = 0
                else:
                    if matrix_life_around[i][j] == 3:
                        matrix_status[i][j] = 1
        # Create a new matrix_life_around with the new matrix_status
        matrix_life_around = get_life_around(my_nodes, matrix_status)
        # Update the time of the nodes
        new_nodes[:, 4] += 1
    return matrix_status, matrix_life_around, new_nodes

dynamic_system(nodes, 1)

(array([[0, 0, 0, 0, 0],
        [0, 1, 0, 1, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0]]),
 array([[0, 0, 0, 0, 0],
        [0, 0, 3, 1, 0],
        [0, 2, 5, 2, 0],
        [0, 0, 3, 1, 0],
        [0, 0, 0, 0, 0]]),
 array([[1, 1, 1, 0, 1],
        [1, 2, 0, 0, 1],
        [1, 3, 1, 0, 1],
        [2, 1, 1, 0, 1],
        [2, 2, 1, 0, 1],
        [2, 3, 1, 0, 1],
        [3, 1, 1, 0, 1],
        [3, 2, 1, 0, 1],
        [3, 3, 0, 0, 1]]))

# Problem B

## Status and Life around matrixes

In [7]:
def get_status_b(nodes):
    matrix_status = np.zeros((numb_nodes, numb_nodes), dtype=int)
    for node in nodes:
        x, y, status, life_around, time = node
        matrix_status[x-1][y-1] = status
    return matrix_status

matrix_status = get_status_b(nodes)
matrix_status

array([[1, 0, 1],
       [1, 1, 1],
       [1, 1, 0]])

In [8]:
def get_life_around_b(nodes, matrix_status):
    matrix_life_around = np.zeros((numb_nodes, numb_nodes), dtype=int)
    for node in nodes:
        x, y, status, life_around, time = node
        for i in range(x-1, x+2):
            for j in range(y-1, y+2):
                # To keep into account that the nodes at the borders don't have 8 neighbours, I add 2 if statements
                if i == 0 or j == 0:
                    continue
                if i > numb_nodes or j > numb_nodes:
                    continue
                #Skip the current node, I want to count the neighbours only
                if i == x and j == y:
                    continue
                if matrix_status[i-1][j-1] == 1:
                    matrix_life_around[x-1][y-1] += 1
    return matrix_life_around

matrix_life_around = get_life_around_b(nodes, matrix_status)
matrix_life_around

array([[2, 5, 2],
       [4, 6, 3],
       [3, 4, 3]])

In [9]:
def dynamic_system_b(my_nodes, n_steps):
    # Create a copy of the original nodes
    new_nodes = np.copy(my_nodes)
    matrix_status = get_status_b(my_nodes)
    matrix_life_around = get_life_around_b(my_nodes, matrix_status)
    for step in range(n_steps):
        for i in range(0, len(matrix_status)):
           for j in range(0, len(matrix_status)):
                if matrix_status[i][j] == 1:
                    if matrix_life_around[i][j] < 2 or matrix_life_around[i][j] > 3:
                        matrix_status[i][j] = 0
                else:
                    if matrix_life_around[i][j] == 3:
                        matrix_status[i][j] = 1
        # Create a new matrix_life_around with the new matrix_status
        matrix_life_around = get_life_around_b(my_nodes, matrix_status)
        # Update the time of the nodes
        new_nodes[:, 4] += 1
    return matrix_status, matrix_life_around, new_nodes

dynamic_system_b(nodes, 1)

(array([[1, 0, 1],
        [0, 0, 1],
        [1, 0, 1]]),
 array([[0, 3, 1],
        [2, 5, 2],
        [0, 3, 1]]),
 array([[1, 1, 1, 0, 1],
        [1, 2, 0, 0, 1],
        [1, 3, 1, 0, 1],
        [2, 1, 1, 0, 1],
        [2, 2, 1, 0, 1],
        [2, 3, 1, 0, 1],
        [3, 1, 1, 0, 1],
        [3, 2, 1, 0, 1],
        [3, 3, 0, 0, 1]]))